### ISSUE TITLE
string array ?

### ISSUE THREAD

**Issue by perrette** [josephalevin/fson#20]
Is there a trick to read a list of strings ?
`{ "char_array" : ["name1", "name22"] }`

**Comment by acroucher** [comment]
At present, there isn't, unfortunately. It looks like FSON never included code for reading arrays of string. I can imagine there could be some problems... but I'll have a look and see if it can be implemented easily.

**Comment by acroucher** [comment]
I have just pushed a branch called char_array, which implements reading of 1-D and 2-D arrays of character variables. Give it a try and let me know if it does what you want.

Note: you have to specify a string length (big enough to hold any string you expect to read) when you declare the array, e.g.:
```fortran
integer, parameter :: str_len = 8
character(len = str_len), allocatable :: x(:)

data => fson_parse("test.json")
call fson_get(data, "char_array", x)
```
It think it is possible to write this in Fortran 2003 without the need to pre-specify a string length (using an array allocatable scalars) but if you have a compiler recent enough to support that, you may as well switch to using [json-fortran](https://github.com/jacobwilliams/json-fortran) instead of fson.

**Comment by perrette** [comment]
Brilliant, thanks !

**Comment by acroucher** [comment]
I just merged it myself into the master branch.
