### ISSUE TITLE
Providing a CMake build

### ISSUE THREAD

**Issue by kprussing** [josephalevin/fson#27]
What are your thoughts on providing a CMake build either along with or instead of the Meson build?  The primary advantage would be allowing users to call the FSON library with 

    find_package(FSON)
    target_link_libraries(client FSON) 

in their CMakeLists.txt and get a "standard" version if they use FSON in many projects.

I put together a [wrapper project](https://github.com/kprussing/fson-cmake-buildsystem) that provides this functionality if you want to take a look (I need to use FSON in a larger project that is already managed using CMake so this was the easy way for me to incorporate the library). If you would like to incorporate those into the main project, let me know and I can redo them as a pull request to the main project.

**Comment by acroucher** [comment]
Yes, I'd be happy for FSON to have a CMake build option alongside make and Meson, if you would like to redo your wrapper as a pull request.

The make and Meson builds have support for building the unit tests, but I don't see that in your CMakeLists.txt (unless I missed it). Could that be added?

Finally, I'm presuming you need to use FSON rather than [json-fortran](https://github.com/jacobwilliams/json-fortran), which already has a CMake build (and lots of other nice stuff that FSON doesn't have).
